services:
  - type: web
    name: proleveling
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_TOKEN
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 3000
